spring.application.name=Grupo3
<<<<<<< HEAD
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_grupo3
spring.datasource.username=admin_grupo3
spring.datasource.password=123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
>>>>>>> 4a2751a (Migración a PostgreSQL para la tabla ObjGasto lista (#16))
